/**
 * Autogenerated by OSUSat Generator -- do not edit manually.
 * OSUSat Messaging Standard Command Table
 */
#ifndef OSUSAT_MESSAGES_H
#define OSUSAT_MESSAGES_H

#include <stdint.h>

typedef enum OSUSatDestination {
    OSUSatDestination_EPS = 0x01,
    OSUSatDestination_PAYLOAD = 0x02,
    OSUSatDestination_OBC = 0x03,
    OSUSatDestination_COMMS = 0x04,
    OSUSatDestination_GSE = 0x05,
    OSUSatDestination_AVIONICS = 0x06,
    OSUSatDestination_BEAVS = 0x07,
} OSUSatDestination;

typedef enum OSUSatMessageType {
    OSUSatMessageType_COMMAND = 0x01,
    OSUSatMessageType_TELEMETRY = 0x02,
    OSUSatMessageType_ACK = 0x03,
    OSUSatMessageType_NACK = 0x04,
    OSUSatMessageType_EXPERIMENT = 0x05,
} OSUSatMessageType;

typedef enum OSUSatCommonCommand {
    OSUSatCommonCommand_HEARTBEAT = 0x01,
    OSUSatCommonCommand_RESET = 0x02,
    OSUSatCommonCommand_ENABLE = 0x03,
    OSUSatCommonCommand_DISABLE = 0x04,
    OSUSatCommonCommand_STATUS = 0x05,
    OSUSatCommonCommand_HEALTHCHECK = 0x06,
} OSUSatCommonCommand;

typedef enum OSUSatEPSCommand {
    OSUSatEPSCommand_ENABLE_RAIL = 0x11,
    OSUSatEPSCommand_DISABLE_RAIL = 0x12,
} OSUSatEPSCommand;

typedef enum OSUSatPAYLOADCommand {
    OSUSatPAYLOADCommand_CAPTURE_IMAGE = 0x13,
    OSUSatPAYLOADCommand_TRANSFER_IMAGE = 0x14,
    OSUSatPAYLOADCommand_ARM = 0x15,
    OSUSatPAYLOADCommand_DISARM = 0x16,
} OSUSatPAYLOADCommand;

typedef enum OSUSatOBCCommand {
    OSUSatOBCCommand_GET_SYSTEM_STATE = 0x17,
} OSUSatOBCCommand;

typedef enum OSUSatGSECommand {
    OSUSatGSECommand_TOGGLE_SAFE_MODE = 0x18,
    OSUSatGSECommand_TOGGLE_MAINTENANCE_MODE = 0x19,
    OSUSatGSECommand_PROBE_SUBSYSTEM_STATUS = 0x1A,
} OSUSatGSECommand;

#endif // OSUSAT_MESSAGES_H
