/**
 * Autogenerated by OSUSat Generator -- do not edit manually.
 * OSUSat Messaging Standard Command Table
 */
#ifndef OSUSAT_MESSAGES_HPP
#define OSUSAT_MESSAGES_HPP

#include <cstdint>

namespace OSUSat {

enum class OSUSatDestination : uint8_t {
    EPS = 0x01,
    PAYLOAD = 0x02,
    OBC = 0x03,
    COMMS = 0x04,
    GSE = 0x05,
    AVIONICS = 0x06,
    BEAVS = 0x07,
};

enum class OSUSatMessageType : uint8_t {
    COMMAND = 0x01,
    TELEMETRY = 0x02,
    ACK = 0x03,
    NACK = 0x04,
    EXPERIMENT = 0x05,
};

enum class OSUSatCommonCommand : uint8_t {
    HEARTBEAT = 0x01,
    RESET = 0x02,
    ENABLE = 0x03,
    DISABLE = 0x04,
    STATUS = 0x05,
    HEALTHCHECK = 0x06,
};

enum class OSUSatEPSCommand : uint8_t {
    ENABLE_RAIL = 0x11,
    DISABLE_RAIL = 0x12,
};

enum class OSUSatPAYLOADCommand : uint8_t {
    CAPTURE_IMAGE = 0x13,
    TRANSFER_IMAGE = 0x14,
    ARM = 0x15,
    DISARM = 0x16,
};

enum class OSUSatOBCCommand : uint8_t {
    GET_SYSTEM_STATE = 0x17,
};

enum class OSUSatGSECommand : uint8_t {
    TOGGLE_SAFE_MODE = 0x18,
    TOGGLE_MAINTENANCE_MODE = 0x19,
    PROBE_SUBSYSTEM_STATUS = 0x1A,
};

}; // namespace OSUSat

#endif // OSUSAT_MESSAGES_HPP
